steps:
  # Install dependencies
  - name: "node:20"
    entrypoint: npm
    args: ["install"]

  # Build the Next.js application
  - name: "node:20"
    entrypoint: npm
    args: ["run", "build"]
    env:
      - "NODE_ENV=production"

  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/notesmart:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/notesmart:latest"
      - "."

  # Push the Docker image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/notesmart:$COMMIT_SHA"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "notesmart"
      - "--image"
      - "gcr.io/$PROJECT_ID/notesmart:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"

# Store the Docker images
images:
  - "gcr.io/$PROJECT_ID/notesmart:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/notesmart:latest"

# Build timeout (default is 10 minutes)
timeout: "1200s"

options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
